- hosts: all
  become: 'true'
  roles:
    - { role: mrLarbi.dns-bind, 
        bind_hostname: "lab1",
        bind_domain_name: "mhermans.prv",
        bind_ip: "192.168.122.69",
        bind_mail: "mhermans.mhermans.prv",
        bind_is_master: yes,
        bind_master_entries : [ {"name": "ansible", "ip":"192.168.122.74"} ]
        bind_listen_on: [ {"ip":"any", port:"53"} ] 
    }
